version: '3.8'

services:
    server:
        image: "dev_basic_gpu_server"
        hostname: "neurosim_env" 
        runtime: nvidia
        ports:
            - "6471:22"
        volumes:
            - /home/jerry/docker_shared:/root
