version: '3.8'

services:
    server:
        build:
            context: ./docker
        hostname: "pydev_env" 
        runtime: nvidia
        ports:
            - "6471:22"
        privileged: true
